### ISSUE TITLE
use libtirpc by defalut 

### ISSUE THREAD

**Issue by Pating** [gluster/nbd-runner#17]
When possible, prefer libtirpc over glibc rpc. 
1. on newer linux with only libtirpc, use libtirpc.
2. on older linux with glibc rpc and WITH libtirpc, use libtirpc by default except when configured with --without-tirpc
3. on old linux with glibc rpc and WITHOUT libtirpc, default to use glibc rpc.
I'll try to do it in fd27/fd28/fd29

**Comment by xiubli** [comment]
Please be careful that in Centos and RHEL Distros as default the libtirpc verion < 1.0.0 there will be some problem, it won't work ad default, I just test the TIRPC v0.2.4, not sure others in v(0.2.4  1.0.0]. I test v1.0.3 and works for me.

**Comment by Pating** [comment]
> Please be careful that in Centos and RHEL Distros as default the libtirpc verion < 1.0.0 there will be some problem, it won't work ad default, I just test the TIRPC v0.2.4, not sure others in v(0.2.4 1.0.0]. I test v1.0.3 and works for me.

Yes, i plan to test this on fd27/fd28/fd29 and make sure libtirpc version >= 1.0.0 

fd27:
libtirpc-devel-1.0.3-2.fc27.x86_64
libtirpc-1.0.3-2.fc27.x86_64
glibc-headers-2.26-15.fc27.x86_64

fd28:
libtirpc-1.0.3-1.rc1.fc28.x86_64
libtirpc-devel-1.0.3-1.rc1.fc28.x86_64

fd29:
libtirpc-1.1.4-2.rc2.fc29.x86_64
libtirpc-devel-1.1.4-2.rc2.fc29.x86_64

**Comment by xiubli** [comment]
https://github.com/gluster/nbd-runner/pull/24

**Comment by xiubli** [comment]
Since this is done, will close it.
